module.exports = {
	GameEvents: {
		ROOM_CONNECTED: 'room_connected',
		ROOM_CHANGE: 'room_change',
		HATCH_STATUS: 'hatch',
		ANSWER: 'answer',
		TELL_ANSWER: 'tell_answer',
		RIGHT_ANSWER: 'right_answer',
		ROUND_START: 'round_start',
		ROUND_END: 'round_end',
		USER_DISCONNECTED: 'user_disconnect',
		ANOTHER_USER_CONNECTED: 'another_user_connected',
		LEADERBOARD_UPDATE: 'leaderboard_update',
		SAY: 'say',
		TELL: 'tell',
		PICK_ANSWER: 'pick_answer',
		CHOOSE_CATEGORY: 'choose_category',
	},
	DEFAULT_TOKEN_REFRESH: (3 * 60 * 60) - (5 * 60),
	DEFAULT_RECONNECT_DELAY: 1000,
};
